FCB1010_CHANNEL = 0

TRACK_NOTES = [ [ i * 10 + j for j in range(0, 10) ] for i in range(0, 10) ]
TRACK_PEDAL_CCS = [ [i * 2, i * 2 + 1] for i in range(0, 10) ]

# MAIN CONTROLLER BANK 00
MAIN_CONTROLLER = \
   ["TRACK_TOGGLE",  "TRACK_TOGGLE", "TRACK_TOGGLE", "TRACK_TOGGLE", "TRACK_TOGGLE", \
    "TRACK_TOGGLE",  "TRACK_TOGGLE", "FIRE_SCENE",   "SCENE_UP",     "SCENE_DOWN", \
    "MASTER_FIRST_FX_DRYWET", "MASTER_TRACK_VOLUME"]

PEDAL_A = 10
PEDAL_B = 11

# SCENE_UP
# SCENE_DOWN
# FIRE_SCENE
# TRACK_TOGGLE
# TRACK_ARM
# TRACK_RECORD_NEW
# FIRST_RACK_CHAIN
# LAST_RACK_CHAIN
# DEVICE_ON XXX

# PEDALS:
# FIRST_RACK_PARAM_1
# FIRST_RACK_PARAM_2
# LAST_RACK_PARAM_1
# LAST_RACK_PARAM_2
# FIRST_FX_PARAM_1
# FIRST_FX_PARAM_2
# LAST_FX_PARAM_1
# LAST_FX_PARAM_2
# FIRST_FX_DRYWET
# LAST_FX_DRYWET
# TRACK_VOLUME
# TRACK_PAN XXX
# TRACK_SEND_1 XXX
# TRACK_SEND_2 XXX
# MASTERFIRST_RACK_PARAM_1
# MASTERFIRST_RACK_PARAM_2
# MASTERLAST_RACK_PARAM_1
# MASTERLAST_RACK_PARAM_2
# MASTERFIRST_FX_PARAM_1
# MASTERFIRST_FX_PARAM_2
# MASTERLAST_FX_PARAM_1
# MASTERLAST_FX_PARAM_2
# MASTERFIRST_FX_DRYWET
# MASTERLAST_FX_DRYWET
# MASTERTRACK_VOLUME
# MASTERTRACK_PAN XXX

TRACK_CONTROLLER = \
    ["FIRST_RACK_CHAIN", "FIRST_RACK_CHAIN", "FIRST_RACK_CHAIN", "FIRST_RACK_CHAIN", "FIRE_SCENE", \
     "TRACK_ARM",        "TRACK_TOGGLE",     "TRACK_RECORD_NEW", "SCENE_UP",         "SCENE_DOWN", \
     "FIRST_FX_DRYWET", "TRACK_VOLUME"]

# MIDI STUFF
STATUS_MASK = 0xF0
CHAN_MASK =  0x0F

CC_STATUS =  0xb0
NOTEON_STATUS = 0x90
NOTEOFF_STATUS = 0x80

STATUS_ON =  0x7f
STATUS_OFF = 0x00
STATUS_OFF2 = 0x40
