# Constants
NUM_TRACKS = 12
NUM_SCENES = 0
NUM_RETURNS = 2

# Channel definitions
VCM_CHANNEL = 12
TRACK_1_CHANNEL = 0

# Control Definitions:
SCENE_WHEEL_DOWN = 89
SCENE_WHEEL_UP = 90
SCENE_WHEEL_CLICK = 87

CROSS_FADER = 8
CUE_VOLUME = 24

#Master Controls:
MASTER_VOLUME = 7
MASTER_PAN = 10

# Track Buttons:
TRACK_STOP = 68
TRACK_PLAY = 69

# Track Controls:
NUM_TRACK_GAINS = 3
TRACK_PAN = 10

TRACK_GAIN_HIGH = 16
TRACK_GAIN_MED = 17
TRACK_GAIN_LOW = 18

TRACK_SEND_A = 19
TRACK_SEND_B = 20

TRACK_RESONANCE = 21
TRACK_FREQUENCY = 22
TRACK_VOLUME = 23

TRACK_HIGH_CUT = 60
TRACK_MED_CUT = 61
TRACK_LOW_CUT = 62

TRACK_MUTE = 63
TRACK_SOLO = 64
TRACK_CF_ASSIGN = 65	# Assign track to Cross Fader

TRACK_VIEW_CLIP = 66
TRACK_VIEW_DEVICE = 67
TRACK_SELECT = TRACK_VIEW_DEVICE

# Return Definitions: (for Return A)
RETURN_PAN = 20
RETURN_VOLUME = 22
RETURN_MUTE = 78

# Array definitions to get around control CC id issues: (These are all in a vertical line)
TRACK_GAIN_CONTROLS = [TRACK_GAIN_HIGH, TRACK_GAIN_MED, TRACK_GAIN_LOW, TRACK_PAN, TRACK_SEND_B, TRACK_FREQUENCY]

# Device Controls:
NUM_DEVICE_BUTTONS = 8

DEVICE_BUTTON_ROW_1 = 70
DEVICE_BUTTON_ROW_2 = 74
DEVICE_BUTTON_ROW_3 = 78 # 78, 79, 80, 81

DEVICE_PARAM_ROW_1 = 12
DEVICE_PARAM_ROW_2 = 16
DEVICE_PARAM_ROW_3 = 20	# row three goes: 20, 21, 24, 10

# Transport Controls:
TRANSPORT_PLAY = 80
TRANSPORT_RECORD = 81
TRANSPORT_LOOP = 84
LOOP_IN = 82
LOOP_OUT = 83 


TEMPO_NUDGE_RIGHT = 86
TEMPO_NUDGE_LEFT = 85
TEMPO_FINE = 25
TEMPO_COURSE = 26